language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - xvfb
cache:
  directories:
  - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  #- "npm run try"
  #- sleep 3 # give server some time to start
script:
  - "npm run try-test"
  #- "npm run tests"
#- xvfb-run wct
#- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s default; fi
after_script:
